version: '{build}'
skip_non_tags: true
image: Visual Studio 2017
build_script:
- ps: |
    dotnet pack -c Release /p:version=$env:APPVEYOR_REPO_TAG_NAME
artifacts:
  - path: '.\src\Utils\bin\Release\*.nupkg'
deploy:
  provider: NuGet
  api_key:
    secure: YuSNfK09e6bNa8EEC2jAsTZP8b8sHN6BDdhrqbI1hRAoqSAUUre5gH8CaW/85NpF
  skip_symbols: false
  artifact: /.*\.nupkg/
cache:
    - '%USERPROFILE%\.nuget\packages -> **\*.csproj'